// Generated by CoffeeScript 1.9.0
var Connector, deployd, path;

path = require('path');

deployd = require(path.normalize(require.main.paths[0] + "/deployd"));

Connector = function(dbOptions) {
  var config, connector;
  config = {
    db: {
      host: dbOptions.host,
      port: dbOptions.port,
      name: dbOptions.name
    }
  };
  return connector = deployd(config);
};

module.exports = Connector;
